FROM python:3.11-slim

RUN apt-get update && apt-get install -y binutils

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r /app/requirements.txt

RUN pyinstaller --onefile /app/main.py

ENTRYPOINT ["/app/dist/main"]